export const districtData = [
    {
      district: "Ariyalur",
      wasteAmount: "150 tons",
      severity: "Low",
      description: "Ariyalur has a relatively low level of waste production. Efforts can be focused on maintaining cleanliness and promoting sustainable waste management practices.",
    },
    {
      district: "Chennai",
      wasteAmount: "500 tons",
      severity: "High",
      description: "Chennai is experiencing a significant waste management challenge, with a high volume of waste generated. Immediate measures are required to address this issue.",
    },
    {
      district: "Coimbatore",
      wasteAmount: "350 tons",
      severity: "Moderate",
      description: "Coimbatore faces a moderate level of waste production. Implementing sustainable waste management practices can help maintain a healthy environment.",
    },
    {
      district: "Cuddalore",
      wasteAmount: "180 tons",
      severity: "Low",
      description: "Cuddalore has a relatively low level of waste generation. Continued efforts towards waste reduction and proper disposal can contribute to a cleaner environment.",
    },
    {
      district: "Dharmapuri",
      wasteAmount: "120 tons",
      severity: "Low",
      description: "Dharmapuri exhibits a low level of waste production. Emphasizing waste segregation and recycling can support sustainable waste management.",
    },
    // // Add more districts and their corresponding data here
    // {
    //     district: "Dharmapuri",
    //     wasteAmount: "120 tons",
    //     severity: "Low",
    //     description: "Dharmapuri exhibits a low level of waste production. Emphasizing waste segregation and recycling can support sustainable waste management.",
    //   },
    //   {
    //     district: "Dindigul",
    //     wasteAmount: "220 tons",
    //     severity: "Moderate",
    //     description: "Dindigul faces a moderate level of waste production. Encouraging community involvement and awareness can contribute to effective waste management practices.",
    //   },
    //   {
    //     district: "Erode",
    //     wasteAmount: "280 tons",
    //     severity: "Moderate",
    //     description: "Erode experiences a moderate level of waste generation. Implementing comprehensive waste management strategies can help mitigate environmental impact.",
    //   },
    //   {
    //     district: "Kanchipuram",
    //     wasteAmount: "380 tons",
    //     severity: "High",
    //     description: "Kanchipuram is grappling with a high level of waste production, necessitating immediate action and sustainable waste management initiatives.",
    //   },
    //   {
    //     district: "Kanyakumari",
    //     wasteAmount: "200 tons",
    //     severity: "Moderate",
    //     description: "Kanyakumari has a moderate level of waste generation. Promoting waste segregation and implementing recycling programs can contribute to a cleaner environment.",
    //   },
    //   {
    //     district: "Karur",
    //     wasteAmount: "150 tons",
    //     severity: "Low",
    //     description: "Karur exhibits a relatively low level of waste production. Encouraging responsible waste disposal practices can help maintain cleanliness and sustainability.",
    //   },  
    //   {
    //     district: "Krishnagiri",
    //     wasteAmount: "180 tons",
    //     severity: "Low",
    //     description: "Krishnagiri exhibits a low level of waste production. Promoting waste reduction and implementing sustainable waste management practices can contribute to a cleaner environment.",
    //   },
    //   {
    //     district: "Madurai",
    //     wasteAmount: "250 tons",
    //     severity: "Moderate",
    //     description: "Madurai has a moderate level of waste generation. Continued efforts towards waste reduction and recycling are necessary for a cleaner city.",
    //   },
    //   {
    //     district: "Nagapattinam",
    //     wasteAmount: "190 tons",
    //     severity: "Low",
    //     description: "Nagapattinam experiences a relatively low level of waste production. Promoting waste segregation and community participation can help maintain a sustainable environment.",
    //   },
    //   {
    //     district: "Namakkal",
    //     wasteAmount: "140 tons",
    //     severity: "Low",
    //     description: "Namakkal exhibits a low level of waste generation. Implementing waste management initiatives and raising awareness can contribute to a cleaner and greener district.",
    //   },
    //   {
    //     district: "Nilgiris",
    //     wasteAmount: "110 tons",
    //     severity: "Low",
    //     description: "Nilgiris has a low level of waste production. Emphasizing eco-friendly practices and promoting waste reduction can help preserve the district's natural beauty.",
    //   },
    //   {
    //     district: "Perambalur",
    //     wasteAmount: "120 tons",
    //     severity: "Low",
    //     description: "Perambalur exhibits a low level of waste production. Implementing effective waste management strategies and promoting recycling can contribute to a cleaner and healthier district.",
    //   },
    //   {
    //     district: "Pudukkottai",
    //     wasteAmount: "170 tons",
    //     severity: "Low",
    //     description: "Pudukkottai experiences a relatively low level of waste generation. Emphasizing waste segregation and community engagement can help maintain a sustainable and eco-friendly district.",
    //   },
    //   {
    //     district: "Ramanathapuram",
    //     wasteAmount: "220 tons",
    //     severity: "Moderate",
    //     description: "Ramanathapuram has a moderate level of waste production. Encouraging responsible waste management practices and implementing recycling initiatives are essential for maintaining cleanliness and sustainability.",
    //   },
    //   {
    //     district: "Salem",
    //     wasteAmount: "320 tons",
    //     severity: "Moderate",
    //     description: "Salem exhibits a moderate level of waste generation. Promoting waste reduction, resource conservation, and community participation can contribute to a cleaner and greener district.",
    //   },
    //   {
    //     district: "Sivaganga",
    //     wasteAmount: "180 tons",
    //     severity: "Low",
    //     description: "Sivaganga experiences a relatively low level of waste production. Implementing sustainable waste management practices and fostering environmental awareness can help maintain a healthy and eco-friendly district.",
    //   },
    //   {
    //     district: "Thanjavur",
    //     wasteAmount: "280 tons",
    //     severity: "Moderate",
    //     description: "Thanjavur has a moderate level of waste generation. Continued efforts towards waste reduction, recycling, and community involvement are essential for a cleaner and sustainable district.",
    //   },
    //   {
    //     district: "Theni",
    //     wasteAmount: "150 tons",
    //     severity: "Low",
    //     description: "Theni exhibits a relatively low level of waste production. Encouraging waste segregation and implementing sustainable waste management practices can contribute to a cleaner and greener district.",
    //   },
    //   {
    //     district: "Thoothukudi (Tuticorin)",
    //     wasteAmount: "300 tons",
    //     severity: "Moderate",
    //     description: "Thoothukudi (Tuticorin) faces a moderate level of waste generation. Emphasizing waste reduction, recycling, and awareness programs can help maintain a sustainable and eco-friendly district.",
    //   },
    //   {
    //     district: "Tiruchirappalli",
    //     wasteAmount: "250 tons",
    //     severity: "Moderate",
    //     description: "Tiruchirappalli experiences a moderate level of waste production. Implementing effective waste management strategies and promoting community participation can contribute to a cleaner and healthier district.",
    //   },
    //   {
    //     district: "Tirunelveli",
    //     wasteAmount: "280 tons",
    //     severity: "Moderate",
    //     description: "Tirunelveli has a moderate level of waste generation. Encouraging responsible waste disposal practices, recycling initiatives, and public awareness campaigns are essential for maintaining a sustainable district.",
    //   },
    //   {
    //     district: "Tiruppur",
    //     wasteAmount: "320 tons",
    //     severity: "High",
    //     description: "Tiruppur is facing a high level of waste production, requiring immediate attention and effective waste management strategies. Sustainable waste reduction measures and industry collaboration are crucial for a cleaner district.",
    //   },
    //   {
    //     district: "Tiruvallur",
    //     wasteAmount: "400 tons",
    //     severity: "High",
    //     description: "Tiruvallur is experiencing a significant waste management challenge, with a high volume of waste generated. Immediate measures are required to address this issue and implement sustainable waste management practices.",
    //   },
    //   {
    //     district: "Tiruvannamalai",
    //     wasteAmount: "270 tons",
    //     severity: "Moderate",
    //     description: "Tiruvannamalai exhibits a moderate level of waste production. Emphasizing waste management practices, promoting recycling, and raising awareness can contribute to a cleaner and greener district.",
    //   },
    //   {
    //     district: "Tiruvarur",
    //     wasteAmount: "180 tons",
    //     severity: "Low",
    //     description: "Tiruvarur has a relatively low level of waste generation. Implementing efficient waste disposal systems and encouraging community participation can help maintain a cleaner and healthier district.",
    //   },
    //   {
    //     district: "Vellore",
    //     wasteAmount: "380 tons",
    //     severity: "High",
    //     description: "Vellore is facing a high level of waste production, requiring immediate attention and effective waste management strategies. Implementing sustainable waste reduction measures and community education are crucial for a cleaner district.",
    //   },
    //   {
    //     district: "Viluppuram",
    //     wasteAmount: "320 tons",
    //     severity: "Moderate",
    //     description: "Viluppuram experiences a moderate level of waste production. Promoting waste segregation, recycling initiatives, and public awareness campaigns can contribute to a sustainable and eco-friendly district.",
    //   },
    //   {
    //     district: "Virudhunagar",
    //     wasteAmount: "210 tons",
    //     severity: "Low",
    //     description: "Virudhunagar exhibits a relatively low level of waste production. Encouraging responsible waste management practices, promoting recycling, and raising awareness can contribute to a cleaner and greener district.",
    //   },
];